# Generated by Django 4.1.4 on 2022-12-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constituency', models.CharField(default='Garissa Township', max_length=40)),
                ('caw', models.CharField(max_length=20)),
                ('polling_center', models.CharField(max_length=100)),
                ('date_of_birth', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=100)),
                ('mname', models.CharField(max_length=50)),
                ('sname', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('id_passport_num', models.CharField(max_length=20)),
            ],
        ),
    ]
