# Generated by Django 4.1.4 on 2022-12-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voterChecker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='mname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
